<?php

/**
 * @file
 * magic360.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function magic360_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "ds" && $api == "ds") {
    return array("version" => "1");
  }
  list($module, $api) = func_get_args();
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function magic360_node_info() {
  $items = array(
    'magic360' => array(
      'name' => t('magic360'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}

